changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: Security
      labels:
        - security
    - title: Bug Fixes
      labels:
        - bug
        - correctness
    - title: Enhancements
      labels:
        - enhancement
        - high-priority
    - title: Testing
      labels:
        - testing
    - title: Other Changes
      labels:
        - "*"
