import assert from "node:assert/strict";
import { test } from "node:test";

import {
  buildReleaseNotes,
  classifyPullRequest,
  extractPullRequestNumbers,
  filterPullRequests,
} from "./release-notes.mjs";

const owner = "arncore";
const repo = "konvoy";

function pr(number, title, files, labels = []) {
  return {
    number,
    title,
    user: { login: "arncore" },
    html_url: `https://github.com/${owner}/${repo}/pull/${number}`,
    labels: labels.map((name) => ({ name })),
    files: files.map((filename) => ({ filename })),
  };
}

test("classifies IntelliJ-only changes only for IntelliJ releases", () => {
  const pullRequest = pr(251, "Add gutter run icons", [
    "editors/intellij/src/main/kotlin/com/konvoy/ide/run/KonvoyTestLineMarkerContributor.kt",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "intellij"), true);
  assert.equal(classifyPullRequest(pullRequest, "cli"), false);
});

test("classifies CLI-only changes only for CLI releases", () => {
  const pullRequest = pr(274, "Fix Rust dependency advisories", [
    "Cargo.toml",
    "Cargo.lock",
    "crates/konvoy-util/src/pom.rs",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "cli"), true);
  assert.equal(classifyPullRequest(pullRequest, "intellij"), false);
});

test("classifies release bumps that touch both surfaces for both releases", () => {
  const pullRequest = pr(275, "Bump release versions", [
    "Cargo.toml",
    "Cargo.lock",
    "editors/intellij/gradle.properties",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "cli"), true);
  assert.equal(classifyPullRequest(pullRequest, "intellij"), true);
});

test("keeps VS Code-only changes out of CLI and IntelliJ release notes", () => {
  const pullRequest = pr(201, "Update VS Code extension", [
    "editors/code/package.json",
    ".github/workflows/vscode-extension.yml",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "cli"), false);
  assert.equal(classifyPullRequest(pullRequest, "intellij"), false);
});

test("keeps IntelliJ documentation-only root edits out of CLI release notes", () => {
  const pullRequest = pr(248, "Bump IntelliJ plugin version", [
    "README.md",
    "editors/intellij/README.md",
    "editors/intellij/gradle.properties",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "cli"), false);
  assert.equal(classifyPullRequest(pullRequest, "intellij"), true);
});

test("filters pull requests by release stream", () => {
  const pullRequests = [
    pr(251, "Add gutter run icons", ["editors/intellij/src/main/kotlin/Main.kt"]),
    pr(274, "Fix Rust dependency advisories", ["Cargo.toml"]),
    pr(275, "Bump release versions", ["Cargo.toml", "editors/intellij/gradle.properties"]),
    pr(201, "Update VS Code extension", ["editors/code/package.json"]),
  ];

  assert.deepEqual(
    filterPullRequests(pullRequests, "cli").map((pullRequest) => pullRequest.number),
    [274, 275],
  );
  assert.deepEqual(
    filterPullRequests(pullRequests, "intellij").map((pullRequest) => pullRequest.number),
    [251, 275],
  );
});

test("renders categorized release notes and full changelog for the selected stream", () => {
  const body = buildReleaseNotes({
    stream: "cli",
    owner,
    repo,
    tag: "v1.2.1",
    previousTag: "v1.2.0",
    pullRequests: [
      pr(274, "Fix Rust dependency advisories", ["Cargo.toml"], ["security"]),
      pr(275, "Bump release versions", ["Cargo.toml"]),
    ],
  });

  assert.match(body, /<!-- Release notes generated by \.github\/scripts\/release-notes\.mjs for cli at v1\.2\.1 -->/);
  assert.match(body, /### Security/);
  assert.match(body, /\* Fix Rust dependency advisories by @arncore in https:\/\/github\.com\/arncore\/konvoy\/pull\/274/);
  assert.match(body, /### Other Changes/);
  assert.match(body, /\* Bump release versions by @arncore in https:\/\/github\.com\/arncore\/konvoy\/pull\/275/);
  assert.match(body, /\*\*Full Changelog\*\*: https:\/\/github\.com\/arncore\/konvoy\/compare\/v1\.2\.0\.\.\.v1\.2\.1/);
});

test("renders an explicit empty message when no PRs match the stream", () => {
  const body = buildReleaseNotes({
    stream: "intellij",
    owner,
    repo,
    tag: "intellij-v1.0.2",
    previousTag: "intellij-v1.0.1",
    pullRequests: [],
  });

  assert.match(body, /No IntelliJ changes were associated with this release\./);
});

test("extracts only the squash merge PR number when a title mentions another issue", () => {
  assert.deepEqual(
    extractPullRequestNumbers("Perf followups + progress bars + UI layering (#267) (#270)"),
    [270],
  );
});
