#!/usr/bin/env node

import fs from "node:fs/promises";

const CATEGORIES = [
  { title: "Security", labels: ["security"] },
  { title: "Bug Fixes", labels: ["bug", "correctness"] },
  { title: "Enhancements", labels: ["enhancement", "high-priority"] },
  { title: "Testing", labels: ["testing"] },
  { title: "Other Changes", labels: ["*"] },
];

const STREAMS = new Set(["cli", "intellij"]);

const CATEGORY_OVERRIDES = new Map([
  [250, "Testing"],
  [251, "Enhancements"],
  [252, "Enhancements"],
  [253, "Enhancements"],
  [254, "Bug Fixes"],
  [255, "Bug Fixes"],
  [256, "Bug Fixes"],
  [257, "Other Changes"],
  [258, "Other Changes"],
  [259, "Other Changes"],
  [260, "Other Changes"],
  [261, "Other Changes"],
  [263, "Other Changes"],
  [264, "Testing"],
  [265, "Testing"],
  [266, "Enhancements"],
  [269, "Enhancements"],
  [270, "Enhancements"],
  [271, "Bug Fixes"],
  [272, "Bug Fixes"],
  [273, "Other Changes"],
  [274, "Security"],
  [275, "Other Changes"],
]);

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg.startsWith("--")) {
      throw new Error(`unexpected argument: ${arg}`);
    }
    const key = arg.slice(2);
    const value = argv[index + 1];
    if (!value || value.startsWith("--")) {
      throw new Error(`missing value for --${key}`);
    }
    args[key] = value;
    index += 1;
  }
  return args;
}

function isIntellijPath(path) {
  return path.startsWith("editors/intellij/") || path === ".github/workflows/intellij-plugin.yml";
}

function isVSCodePath(path) {
  return path.startsWith("editors/code/") || path === ".github/workflows/vscode-extension.yml";
}

function isEditorOnlyPath(path) {
  return isIntellijPath(path) || isVSCodePath(path);
}

function isCliPath(path) {
  return (
    path === "Cargo.toml" ||
    path === "Cargo.lock" ||
    path === ".github/release.yml" ||
    path === ".github/workflows/ci.yml" ||
    path === ".github/workflows/release.yml" ||
    path.startsWith("crates/") ||
    path.startsWith("tests/")
  );
}

export function classifyPullRequest(pullRequest, stream) {
  const filenames = pullRequest.files.map((file) => file.filename);

  if (stream === "intellij") {
    return filenames.some(isIntellijPath);
  }

  if (stream === "cli") {
    return filenames.some((filename) => isCliPath(filename) && !isEditorOnlyPath(filename));
  }

  throw new Error(`unsupported release stream: ${stream}`);
}

export function filterPullRequests(pullRequests, stream) {
  return pullRequests.filter((pullRequest) => classifyPullRequest(pullRequest, stream));
}

function categoryByLabel(pullRequest) {
  const labels = new Set(pullRequest.labels.map((label) => label.name));
  return CATEGORIES.find((category) => {
    if (category.labels.includes("*")) {
      return false;
    }
    return category.labels.some((label) => labels.has(label));
  });
}

function categoryByTitle(pullRequest) {
  const title = pullRequest.title.toLowerCase();

  if (/\b(security|advisories|advisory|vulnerabilit|dependabot|audit)\b/.test(title)) {
    return CATEGORIES.find((category) => category.title === "Security");
  }

  if (/\b(fix|bug|failure|fail|regression|broken|compatibility)\b/.test(title)) {
    return CATEGORIES.find((category) => category.title === "Bug Fixes");
  }

  if (/\b(test|tests|testing|coverage|ci)\b/.test(title)) {
    return CATEGORIES.find((category) => category.title === "Testing");
  }

  if (
    /\b(add|support|parallelize|perf|performance|typed|type-safety|enum|progress|diagnostics|completion|clickable)\b/.test(
      title,
    )
  ) {
    return CATEGORIES.find((category) => category.title === "Enhancements");
  }

  return undefined;
}

export function categoryForPullRequest(pullRequest) {
  const override = CATEGORY_OVERRIDES.get(pullRequest.number);
  if (override) {
    return CATEGORIES.find((category) => category.title === override);
  }

  return (
    categoryByLabel(pullRequest) ??
    categoryByTitle(pullRequest) ??
    CATEGORIES.find((category) => category.title === "Other Changes")
  );
}

function streamDisplayName(stream) {
  return stream === "intellij" ? "IntelliJ" : "CLI";
}

export function buildReleaseNotes({ stream, owner, repo, tag, previousTag, pullRequests }) {
  const lines = [
    `<!-- Release notes generated by .github/scripts/release-notes.mjs for ${stream} at ${tag} -->`,
    "",
    "## What's Changed",
  ];

  if (pullRequests.length === 0) {
    lines.push(`No ${streamDisplayName(stream)} changes were associated with this release.`);
  } else {
    const grouped = new Map(CATEGORIES.map((category) => [category.title, []]));
    for (const pullRequest of pullRequests) {
      grouped.get(categoryForPullRequest(pullRequest).title).push(pullRequest);
    }

    for (const category of CATEGORIES) {
      const categoryPullRequests = grouped.get(category.title);
      if (categoryPullRequests.length === 0) {
        continue;
      }

      if (lines.at(-1) !== "## What's Changed") {
        lines.push("");
      }
      lines.push(`### ${category.title}`);
      for (const pullRequest of categoryPullRequests) {
        lines.push(
          `* ${pullRequest.title} by @${pullRequest.user.login} in ${pullRequest.html_url}`,
        );
      }
    }
  }

  if (previousTag) {
    lines.push(
      "",
      `**Full Changelog**: https://github.com/${owner}/${repo}/compare/${previousTag}...${tag}`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

class GitHubClient {
  constructor({ owner, repo, token }) {
    this.owner = owner;
    this.repo = repo;
    this.token = token;
  }

  async request(path) {
    const response = await fetch(`https://api.github.com${path}`, {
      headers: {
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}),
      },
    });

    if (!response.ok) {
      throw new Error(`GitHub API request failed (${response.status}): ${path}`);
    }

    return response.json();
  }

  async paginated(path) {
    const results = [];
    let page = 1;

    while (true) {
      const separator = path.includes("?") ? "&" : "?";
      const items = await this.request(`${path}${separator}per_page=100&page=${page}`);
      results.push(...items);
      if (items.length < 100) {
        return results;
      }
      page += 1;
    }
  }

  async releases() {
    return this.paginated(`/repos/${this.owner}/${this.repo}/releases`);
  }

  async compare(previousTag, tag) {
    return this.request(`/repos/${this.owner}/${this.repo}/compare/${previousTag}...${tag}`);
  }

  async commitPullRequests(sha) {
    return this.paginated(`/repos/${this.owner}/${this.repo}/commits/${sha}/pulls`);
  }

  async pullRequest(number) {
    return this.request(`/repos/${this.owner}/${this.repo}/pulls/${number}`);
  }

  async pullRequestFiles(number) {
    return this.paginated(`/repos/${this.owner}/${this.repo}/pulls/${number}/files`);
  }
}

function releaseMatchesStream(release, stream) {
  if (stream === "intellij") {
    return release.tag_name.startsWith("intellij-v");
  }
  return /^v\d/.test(release.tag_name);
}

async function findPreviousTag(client, stream, tag) {
  const releases = await client.releases();
  const release = releases.find((candidate) => {
    return candidate.tag_name !== tag && releaseMatchesStream(candidate, stream);
  });
  return release?.tag_name;
}

export function extractPullRequestNumbers(message) {
  const numbers = new Set();
  const firstLine = message.split("\n", 1)[0];
  const mergePullRequest = firstLine.match(/^Merge pull request #(\d+)/);
  if (mergePullRequest) {
    return [Number(mergePullRequest[1])];
  }

  const squashMerge = firstLine.match(/\(#(\d+)\)$/);
  if (squashMerge) {
    numbers.add(Number(squashMerge[1]));
  }

  return [...numbers];
}

function prNumbersFromCommitMessage(message) {
  return new Set(extractPullRequestNumbers(message));
}

async function pullRequestNumbersForRange(client, previousTag, tag) {
  const comparison = await client.compare(previousTag, tag);
  const numbers = new Set();

  for (const commit of comparison.commits) {
    for (const number of prNumbersFromCommitMessage(commit.commit.message)) {
      numbers.add(number);
    }
  }

  for (const commit of comparison.commits) {
    if (prNumbersFromCommitMessage(commit.commit.message).size > 0) {
      continue;
    }
    for (const pullRequest of await client.commitPullRequests(commit.sha)) {
      numbers.add(pullRequest.number);
    }
  }

  return [...numbers].sort((left, right) => left - right);
}

async function pullRequestsWithFiles(client, numbers) {
  const pullRequests = [];
  for (const number of numbers) {
    const pullRequest = await client.pullRequest(number);
    pullRequest.files = await client.pullRequestFiles(number);
    pullRequests.push(pullRequest);
  }
  return pullRequests;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const stream = args.stream;
  if (!STREAMS.has(stream)) {
    throw new Error(`--stream must be one of: ${[...STREAMS].join(", ")}`);
  }

  const repoSlug = args.repo ?? process.env.GITHUB_REPOSITORY;
  if (!repoSlug) {
    throw new Error("--repo or GITHUB_REPOSITORY is required");
  }

  const [owner, repo] = repoSlug.split("/");
  const tag = args.tag ?? process.env.GITHUB_REF_NAME;
  if (!tag) {
    throw new Error("--tag or GITHUB_REF_NAME is required");
  }

  const client = new GitHubClient({
    owner,
    repo,
    token: process.env.GITHUB_TOKEN,
  });
  const previousTag = args["previous-tag"] ?? (await findPreviousTag(client, stream, tag));
  const pullRequests = previousTag
    ? await pullRequestsWithFiles(client, await pullRequestNumbersForRange(client, previousTag, tag))
    : [];
  const matchingPullRequests = filterPullRequests(pullRequests, stream);
  const body = buildReleaseNotes({
    stream,
    owner,
    repo,
    tag,
    previousTag,
    pullRequests: matchingPullRequests,
  });

  if (args.output) {
    await fs.writeFile(args.output, body);
  } else {
    process.stdout.write(body);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
