import assert from "node:assert/strict";
import { test } from "node:test";

import {
  buildReleaseNotes,
  categoryForPullRequest,
  classifyPullRequest,
  extractPullRequestNumbers,
  filterPullRequests,
  isExcludedFromNotes,
} from "./release-notes.mjs";

const owner = "arncore";
const repo = "konvoy";

function pr(number, title, files, labels = []) {
  return {
    number,
    title,
    user: { login: "arncore" },
    html_url: `https://github.com/${owner}/${repo}/pull/${number}`,
    labels: labels.map((name) => ({ name })),
    files: files.map((filename) => ({ filename })),
  };
}

test("classifies IntelliJ-only changes only for IntelliJ releases", () => {
  const pullRequest = pr(251, "Add gutter run icons", [
    "editors/intellij/src/main/kotlin/com/konvoy/ide/run/KonvoyTestLineMarkerContributor.kt",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "intellij"), true);
  assert.equal(classifyPullRequest(pullRequest, "cli"), false);
});

test("classifies CLI-only changes only for CLI releases", () => {
  const pullRequest = pr(274, "Fix Rust dependency advisories", [
    "Cargo.toml",
    "Cargo.lock",
    "crates/konvoy-util/src/pom.rs",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "cli"), true);
  assert.equal(classifyPullRequest(pullRequest, "intellij"), false);
});

test("classifies release bumps that touch both surfaces for both releases", () => {
  const pullRequest = pr(275, "Bump release versions", [
    "Cargo.toml",
    "Cargo.lock",
    "editors/intellij/gradle.properties",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "cli"), true);
  assert.equal(classifyPullRequest(pullRequest, "intellij"), true);
});

test("keeps VS Code-only changes out of CLI and IntelliJ release notes", () => {
  const pullRequest = pr(201, "Update VS Code extension", [
    "editors/code/package.json",
    ".github/workflows/vscode-extension.yml",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "cli"), false);
  assert.equal(classifyPullRequest(pullRequest, "intellij"), false);
});

test("keeps IntelliJ documentation-only root edits out of CLI release notes", () => {
  const pullRequest = pr(248, "Bump IntelliJ plugin version", [
    "README.md",
    "editors/intellij/README.md",
    "editors/intellij/gradle.properties",
  ]);

  assert.equal(classifyPullRequest(pullRequest, "cli"), false);
  assert.equal(classifyPullRequest(pullRequest, "intellij"), true);
});

test("filters by release stream and drops version-bump PRs", () => {
  const pullRequests = [
    pr(251, "Add gutter run icons", ["editors/intellij/src/main/kotlin/Main.kt"]),
    pr(274, "Fix Rust dependency advisories", ["Cargo.toml"]),
    // Touches both surfaces, but a version bump → excluded from both streams' notes.
    pr(275, "Bump release versions", ["Cargo.toml", "editors/intellij/gradle.properties"]),
    pr(201, "Update VS Code extension", ["editors/code/package.json"]),
  ];

  assert.deepEqual(
    filterPullRequests(pullRequests, "cli").map((pullRequest) => pullRequest.number),
    [274],
  );
  assert.deepEqual(
    filterPullRequests(pullRequests, "intellij").map((pullRequest) => pullRequest.number),
    [251],
  );
});

test("excludes version-bump PRs but not feature PRs", () => {
  assert.equal(
    isExcludedFromNotes(pr(308, "Bump release versions: CLI 1.3.0, IntelliJ plugin 1.1.0", ["Cargo.toml"])),
    true,
  );
  assert.equal(
    isExcludedFromNotes(pr(283, "codegen (1/5): [codegen.openapi] manifest schema + validation", ["x"])),
    false,
  );
});

test("categorizes codegen/generate feature titles as Enhancements", () => {
  assert.equal(
    categoryForPullRequest(
      pr(283, "codegen (1/5): [codegen.openapi] manifest schema + validation", [
        "crates/konvoy-config/src/manifest.rs",
      ]),
    ).title,
    "Enhancements",
  );
  assert.equal(
    categoryForPullRequest(
      pr(306, "intellij: `konvoy generate` run configuration + Build-menu action", [
        "editors/intellij/src/main/kotlin/X.kt",
      ]),
    ).title,
    "Enhancements",
  );
});

test("override keeps the codegen docs PR out of Bug Fixes", () => {
  // #301's title contains "regression fix" but it's a docs/polish PR.
  assert.equal(
    categoryForPullRequest(
      pr(301, "codegen (5/5): docs + polish (README, error/doc copy, smoke regression fix)", [
        "README.md",
      ]),
    ).title,
    "Other Changes",
  );
});

test("renders categorized release notes and full changelog for the selected stream", () => {
  const body = buildReleaseNotes({
    stream: "cli",
    owner,
    repo,
    tag: "v1.2.1",
    previousTag: "v1.2.0",
    pullRequests: [
      pr(274, "Fix Rust dependency advisories", ["Cargo.toml"], ["security"]),
      pr(275, "Bump release versions", ["Cargo.toml"]),
    ],
  });

  assert.match(body, /<!-- Release notes generated by \.github\/scripts\/release-notes\.mjs for cli at v1\.2\.1 -->/);
  assert.match(body, /### Security/);
  assert.match(body, /\* Fix Rust dependency advisories by @arncore in https:\/\/github\.com\/arncore\/konvoy\/pull\/274/);
  assert.match(body, /### Other Changes/);
  assert.match(body, /\* Bump release versions by @arncore in https:\/\/github\.com\/arncore\/konvoy\/pull\/275/);
  assert.match(body, /\*\*Full Changelog\*\*: https:\/\/github\.com\/arncore\/konvoy\/compare\/v1\.2\.0\.\.\.v1\.2\.1/);
});

test("infers categories from unlabeled PR titles", () => {
  assert.equal(
    categoryForPullRequest(pr(274, "Fix Rust dependency advisories", ["Cargo.toml"])).title,
    "Security",
  );
  assert.equal(
    categoryForPullRequest(pr(256, "Fix dep resolution bug", ["crates/konvoy-engine/src/build.rs"]))
      .title,
    "Bug Fixes",
  );
  assert.equal(
    categoryForPullRequest(pr(266, "Parallelize hashing/downloads", ["crates/konvoy-util/src/hash.rs"]))
      .title,
    "Enhancements",
  );
  assert.equal(
    categoryForPullRequest(pr(265, "Add 15 smoke tests", ["tests/smoke/tests.sh"])).title,
    "Testing",
  );
});

test("label categories take precedence over title inference", () => {
  assert.equal(
    categoryForPullRequest(pr(300, "Fix flaky test output", ["crates/foo/src/lib.rs"], ["testing"]))
      .title,
    "Testing",
  );
});

test("reviewed release PR overrides preserve deliberate category placement", () => {
  assert.equal(
    categoryForPullRequest(pr(251, "Add gutter run icons for main and test functions", [
      "editors/intellij/src/main/kotlin/Main.kt",
    ])).title,
    "Enhancements",
  );
  assert.equal(
    categoryForPullRequest(pr(260, "Add helper methods, deduplicate repeated patterns", [
      "crates/konvoy-engine/src/build.rs",
    ])).title,
    "Other Changes",
  );
  assert.equal(
    categoryForPullRequest(pr(271, "Support CLT-only macOS Kotlin/Native builds", [
      "crates/konvoy-konanc/src/invoke.rs",
    ])).title,
    "Bug Fixes",
  );
});

test("renders an explicit empty message when no PRs match the stream", () => {
  const body = buildReleaseNotes({
    stream: "intellij",
    owner,
    repo,
    tag: "intellij-v1.0.2",
    previousTag: "intellij-v1.0.1",
    pullRequests: [],
  });

  assert.match(body, /No IntelliJ changes were associated with this release\./);
});

test("extracts only the squash merge PR number when a title mentions another issue", () => {
  assert.deepEqual(
    extractPullRequestNumbers("Perf followups + progress bars + UI layering (#267) (#270)"),
    [270],
  );
});
