//! Build script for konvoy-engine.
//!
//! Scans `libraries/*.toml` and generates a Rust source file that embeds each
//! descriptor at compile time. The library name is derived from the filename
//! (e.g. `kotlinx-coroutines.toml` → `"kotlinx-coroutines"`), so adding a new
//! library is just dropping a `.toml` file — no Rust code changes needed.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::fs;
use std::path::Path;
use std::{env, io::Write};

fn main() {
    let libraries_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../libraries");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("library_descriptors.rs");

    println!("cargo::rerun-if-changed={}", libraries_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();

    if libraries_dir.is_dir() {
        let mut paths: Vec<_> = fs::read_dir(&libraries_dir)
            .expect("cannot read libraries directory")
            .filter_map(Result::ok)
            .filter(|e| e.path().extension().is_some_and(|ext| ext == "toml"))
            .collect();

        // Sort for deterministic output.
        paths.sort_by_key(std::fs::DirEntry::file_name);

        for entry in &paths {
            let path = entry.path();
            let stem = path
                .file_stem()
                .expect("file has no stem")
                .to_str()
                .expect("non-UTF-8 filename");

            // Emit a rerun-if-changed for each individual file too.
            println!("cargo::rerun-if-changed={}", path.display());

            entries.push((stem.to_owned(), path.display().to_string()));
        }
    }

    let mut out = fs::File::create(&dest).expect("cannot create generated file");

    writeln!(out, "/// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(
        out,
        "pub(crate) const LIBRARY_SOURCES: &[(&str, &str)] = &["
    )
    .unwrap();
    for (name, path) in &entries {
        writeln!(out, "    (\"{name}\", include_str!(\"{path}\")),").unwrap();
    }
    writeln!(out, "];").unwrap();
}
